from phoenix6 import CANBus, configs, hardware, signals, swerve, units
from wpimath.units import inchesToMeters

from constants.shot_calculator_constants import default_field_type
from subsystems.swerve_drivetrain import SwerveDrivetrain


class SwerveDrivetrainConstants:
    """
    Module geometry, gains, and driving limits for the swerve drivetrain.

    Most of this was generated by the 2026 Tuner X Swerve Project Generator, so values such as
    the gear ratios and encoder offsets should be changed there and re-exported rather than
    edited by hand. The teleop shaping values above them are tuned during driver practice.

    https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
    """

    # Robot configuration
    _robot_length = 0.838  # Length of the robot in meters
    _robot_width = 0.838  # Width of the robot in meters

    # Max speeds of drivetrain
    _max_linear_speed = 5.25  # Max linear speed in meters per second
    _max_angular_speed = 16  # Max angular velocity in radians per second

    # Time in seconds to ramp teleop commands from rest to max speed. The ramp only shapes the
    # commanded speed; battery draw during acceleration is bounded by the current limits below.
    _linear_accel_time = 0.25
    _angular_accel_time = 0.25

    # The most a teleop command may change in one 20 ms loop, which works out to reaching max
    # speed in the accel times above.
    _max_linear_rate_of_change = _max_linear_speed / _linear_accel_time * 0.020
    _max_angular_rate_of_change = _max_angular_speed / _angular_accel_time * 0.020

    # Teleop throttle scaling as a fraction of the physical max speed. Tune during driver practice.
    _teleop_precision_scale = 0.25  # Applied when the left trigger is held
    _teleop_default_scale = 0.50  # Applied when no trigger is held
    _teleop_turbo_scale = 1.00  # Applied when both triggers are held

    # Rotation gets its own scale so turning is not twitchy at the high physical max
    _teleop_rotation_scale = 0.55

    # Stick deadbands as a fraction of full stick travel
    _teleop_translation_deadband = 0.075
    _teleop_rotation_deadband = 0.075

    # Frequency to run the odometry loop at in hertz
    _odometry_update_frequency = 250.0

    # Number of times to attempt to configure the license-probe device built ahead of the
    # swerve devices. Sized so retries span the several seconds after code start when Phoenix
    # license checks can reject configs on a pro bus.
    _num_config_attempts = 20

    _field_type = default_field_type

    # The steer motor uses any SwerveModule.SteerRequestType control request with the
    # output type specified by SwerveModuleConstants.SteerMotorClosedLoopOutput
    _steer_gains = (
        configs.Slot0Configs()
        .with_k_p(25)
        .with_k_i(0)
        .with_k_d(0)
        .with_k_s(0.1)
        .with_k_v(1.5)
        .with_static_feedforward_sign(signals.StaticFeedforwardSignValue.USE_CLOSED_LOOP_SIGN)
    )

    # When using closed-loop control, the drive motor uses the control
    # output type specified by SwerveModuleConstants.DriveMotorClosedLoopOutput
    _drive_gains = (
        configs.Slot0Configs().with_k_p(0.1).with_k_i(0).with_k_d(0).with_k_s(0).with_k_v(0.124)
    )

    # The closed-loop output type to use for the steer motors;
    # This affects the PID/FF gains for the steer motors
    _steer_closed_loop_output = swerve.ClosedLoopOutputType.VOLTAGE

    # The closed-loop output type to use for the drive motors;
    # This affects the PID/FF gains for the drive motors
    _drive_closed_loop_output = swerve.ClosedLoopOutputType.VOLTAGE

    # The type of motor used for the drive motor
    _drive_motor_type = swerve.DriveMotorArrangement.TALON_FX_INTEGRATED

    # The type of motor used for the drive motor
    _steer_motor_type = swerve.SteerMotorArrangement.TALON_FX_INTEGRATED

    # The remote sensor feedback type to use for the steer motors;
    # When not Pro-licensed, Fused*/Sync* automatically fall back to Remote*
    _steer_feedback_type = swerve.SteerFeedbackType.FUSED_CANCODER

    # The stator current at which the wheels start to slip, which doubles as the drive motors'
    # stator current limit. Pushing past it only spins the wheels.
    # https://v6.docs.ctr-electronics.com/en/2024/docs/api-reference/mechanisms/swerve/swerve-builder-api.html
    # https://v6.docs.ctr-electronics.com/en/latest/docs/hardware-reference/talonfx/improving-performance-with-current-limits.html#preventing-brownouts
    _slip_current: units.ampere = 50.0

    # Initial configs for the drive and steer motors and the azimuth encoder; these cannot be null.
    # Some configs will be overwritten; check the `with_*_initial_configs()` API documentation.
    # https://api.ctr-electronics.com/phoenix6/latest/python/autoapi/phoenix6/swerve/swerve_module_constants/index.html#phoenix6.swerve.swerve_module_constants.SwerveModuleConstants.drive_motor_initial_configs
    _drive_initial_configs = (
        configs.TalonFXConfiguration()
        .with_motor_output(
            configs.MotorOutputConfigs().with_neutral_mode(signals.NeutralModeValue.BRAKE)
        )
        .with_current_limits(
            configs.CurrentLimitsConfigs()
            # Supply-side limit on the drive motors to help avoid brownouts. It must sit below
            # the 50 A stator (slip) limit to ever engage, since supply current cannot exceed
            # stator current; the slip limit itself is applied via with_slip_current on the
            # module constants factory. Sustained draw drops further so a multi-second pushing
            # match cannot hold four motors at full supply draw.
            .with_supply_current_limit(40.0)
            .with_supply_current_limit_enable(True)
            .with_supply_current_lower_limit(30.0)
            .with_supply_current_lower_time(1.0)
        )
    )

    _steer_initial_configs = (
        configs.TalonFXConfiguration()
        .with_motor_output(
            configs.MotorOutputConfigs().with_neutral_mode(signals.NeutralModeValue.BRAKE)
        )
        .with_current_limits(
            configs.CurrentLimitsConfigs()
            # Swerve azimuth does not require much torque output, so we can set a relatively low
            # stator current limit to help avoid brownouts without impacting performance.
            .with_stator_current_limit(40.0)
            .with_stator_current_limit_enable(True)
        )
    )

    # Configs for the azimuth encoders
    _encoder_initial_configs = configs.CANcoderConfiguration()

    # Configs for the Pigeon 2
    _pigeon_configs = configs.Pigeon2Configuration().with_mount_pose(
        configs.MountPoseConfigs()
        .with_mount_pose_yaw(-0.3205808699131012)
        .with_mount_pose_pitch(-0.43110448122024536)
        .with_mount_pose_roll(0.033288005739450455)
    )

    # CAN bus that the devices are located on;
    # All swerve devices must share the same CAN bus
    canbus = CANBus("Drivetrain")

    # Theoretical free speed (m/s) at 12 V applied output;
    speed_at_12_volts: units.meters_per_second = 5.44

    # Turning a module also drags its drive motor along; every azimuth rotation costs this many
    # drive turns. Tuner X generates the value, so a non-zero number here needs no further work.
    # https://www.chiefdelphi.com/t/kcoupleratio-in-ctre-swerve/483380
    _couple_ratio = 5.4

    _drive_gear_ratio = 5.67
    _steer_gear_ratio = 12.1
    _wheel_radius: units.meter = 0.04953  # inchesToMeters(1.974) 1.919048156363767

    _invert_left_side = False
    _invert_right_side = True

    _pigeon_id = 4

    # These are only used for simulation
    _steer_inertia: units.kilogram_square_meter = 0.01
    _drive_inertia: units.kilogram_square_meter = 0.035

    # Simulated voltage necessary to overcome friction
    _steer_friction_voltage: units.volt = 0.2
    _drive_friction_voltage: units.volt = 0.2

    drivetrain_constants = (
        swerve.SwerveDrivetrainConstants()
        .with_can_bus_name(canbus.name)
        .with_pigeon2_id(_pigeon_id)
        .with_pigeon2_configs(_pigeon_configs)
    )

    _constants_creator: swerve.SwerveModuleConstantsFactory[
        configs.TalonFXConfiguration,
        configs.TalonFXConfiguration,
        configs.CANcoderConfiguration,
    ] = (
        swerve.SwerveModuleConstantsFactory()
        .with_drive_motor_gear_ratio(_drive_gear_ratio)
        .with_steer_motor_gear_ratio(_steer_gear_ratio)
        .with_coupling_gear_ratio(_couple_ratio)
        .with_wheel_radius(_wheel_radius)
        .with_steer_motor_gains(_steer_gains)
        .with_drive_motor_gains(_drive_gains)
        .with_steer_motor_closed_loop_output(_steer_closed_loop_output)
        .with_drive_motor_closed_loop_output(_drive_closed_loop_output)
        .with_slip_current(_slip_current)
        .with_speed_at12_volts(speed_at_12_volts)
        .with_drive_motor_type(_drive_motor_type)
        .with_steer_motor_type(_steer_motor_type)
        .with_feedback_source(_steer_feedback_type)
        .with_drive_motor_initial_configs(_drive_initial_configs)
        .with_steer_motor_initial_configs(_steer_initial_configs)
        .with_encoder_initial_configs(_encoder_initial_configs)
        .with_steer_inertia(_steer_inertia)
        .with_drive_inertia(_drive_inertia)
        .with_steer_friction_voltage(_steer_friction_voltage)
        .with_drive_friction_voltage(_drive_friction_voltage)
    )

    # Front Left
    _front_left_drive_motor_id = 10
    _front_left_steer_motor_id = 20
    _front_left_encoder_id = 0
    _front_left_encoder_offset: units.rotation = -0.26171875
    _front_left_steer_motor_inverted = True
    _front_left_encoder_inverted = False

    _front_left_x_pos: units.meter = inchesToMeters(9)
    _front_left_y_pos: units.meter = inchesToMeters(9)

    # Front Right
    _front_right_drive_motor_id = 11
    _front_right_steer_motor_id = 21
    _front_right_encoder_id = 1
    _front_right_encoder_offset: units.rotation = -0.21533203125
    _front_right_steer_motor_inverted = True
    _front_right_encoder_inverted = False

    _front_right_x_pos: units.meter = inchesToMeters(9)
    _front_right_y_pos: units.meter = inchesToMeters(-9)

    # Back Left
    _back_left_drive_motor_id = 12
    _back_left_steer_motor_id = 22
    _back_left_encoder_id = 2
    _back_left_encoder_offset: units.rotation = -0.048095703125
    _back_left_steer_motor_inverted = True
    _back_left_encoder_inverted = False

    _back_left_x_pos: units.meter = inchesToMeters(-9)
    _back_left_y_pos: units.meter = inchesToMeters(9)

    # Back Right
    _back_right_drive_motor_id = 13
    _back_right_steer_motor_id = 23
    _back_right_encoder_id = 3
    _back_right_encoder_offset: units.rotation = 0.329345703125
    _back_right_steer_motor_inverted = True
    _back_right_encoder_inverted = False

    _back_right_x_pos: units.meter = inchesToMeters(-9)
    _back_right_y_pos: units.meter = inchesToMeters(-9)

    front_left = _constants_creator.create_module_constants(
        _front_left_steer_motor_id,
        _front_left_drive_motor_id,
        _front_left_encoder_id,
        _front_left_encoder_offset,
        _front_left_x_pos,
        _front_left_y_pos,
        _invert_left_side,
        _front_left_steer_motor_inverted,
        _front_left_encoder_inverted,
    )
    front_right = _constants_creator.create_module_constants(
        _front_right_steer_motor_id,
        _front_right_drive_motor_id,
        _front_right_encoder_id,
        _front_right_encoder_offset,
        _front_right_x_pos,
        _front_right_y_pos,
        _invert_right_side,
        _front_right_steer_motor_inverted,
        _front_right_encoder_inverted,
    )
    back_left = _constants_creator.create_module_constants(
        _back_left_steer_motor_id,
        _back_left_drive_motor_id,
        _back_left_encoder_id,
        _back_left_encoder_offset,
        _back_left_x_pos,
        _back_left_y_pos,
        _invert_left_side,
        _back_left_steer_motor_inverted,
        _back_left_encoder_inverted,
    )
    back_right = _constants_creator.create_module_constants(
        _back_right_steer_motor_id,
        _back_right_drive_motor_id,
        _back_right_encoder_id,
        _back_right_encoder_offset,
        _back_right_x_pos,
        _back_right_y_pos,
        _invert_right_side,
        _back_right_steer_motor_inverted,
        _back_right_encoder_inverted,
    )

    @classmethod
    def create_drivetrain(cls) -> SwerveDrivetrain:
        """
        Create a SwerveDrivetrain instance using the configured constant values.

        :returns: Configured swerve drivetrain subsystem.
        :rtype: subsystems.swerve_drivetrain.SwerveDrivetrain
        """
        return SwerveDrivetrain(
            hardware.TalonFX,
            hardware.TalonFX,
            hardware.CANcoder,
            cls.drivetrain_constants,
            [
                cls.front_left,
                cls.front_right,
                cls.back_left,
                cls.back_right,
            ],
            cls._num_config_attempts,
            cls._odometry_update_frequency,
            cls._max_linear_speed,
            cls._max_angular_speed,
            cls._max_linear_rate_of_change,
            cls._max_angular_rate_of_change,
            cls._teleop_precision_scale,
            cls._teleop_default_scale,
            cls._teleop_turbo_scale,
            cls._teleop_rotation_scale,
            cls._teleop_translation_deadband,
            cls._teleop_rotation_deadband,
            cls._field_type,
            cls._wheel_radius,
        )
